// Generated by scripts/generate.js from js.h. Do not edit.

module.exports = function bindings(rt, js) {
  return {
    js_create_platform(loop, options, result) {
      return rt.call(false, () => {
        const value = js.create_platform(rt, loop >>> 0, options >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_destroy_platform(platform) {
      return rt.call(false, () => {
        js.destroy_platform(rt, platform >>> 0)
      })
    },

    js_get_platform_identifier(platform, result) {
      return rt.call(false, () => {
        const value = js.get_platform_identifier(rt, platform >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_platform_version(platform, result) {
      return rt.call(false, () => {
        const value = js.get_platform_version(rt, platform >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_platform_limits(platform, result) {
      return rt.call(false, () => {
        js.get_platform_limits(rt, platform >>> 0, result >>> 0)
      })
    },

    js_get_platform_loop(platform, result) {
      return rt.call(false, () => {
        const value = js.get_platform_loop(rt, platform >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_create_env(loop, platform, options, result) {
      return rt.call(false, () => {
        const value = js.create_env(rt, loop >>> 0, platform >>> 0, options >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_destroy_env(env) {
      return rt.call(false, () => {
        js.destroy_env(rt)
      })
    },

    js_on_uncaught_exception(env, cb, data) {
      return rt.call(false, () => {
        js.on_uncaught_exception(rt, cb >>> 0, data >>> 0)
      })
    },

    js_on_unhandled_rejection(env, cb, data) {
      return rt.call(false, () => {
        js.on_unhandled_rejection(rt, cb >>> 0, data >>> 0)
      })
    },

    js_on_dynamic_import(env, cb, data) {
      return rt.call(false, () => {
        js.on_dynamic_import(rt, cb >>> 0, data >>> 0)
      })
    },

    js_get_env_loop(env, result) {
      return rt.call(false, () => {
        const value = js.get_env_loop(rt, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_env_platform(env, result) {
      return rt.call(false, () => {
        const value = js.get_env_platform(rt, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_open_handle_scope(env, result) {
      return rt.call(true, () => {
        const value = js.open_handle_scope(rt, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_close_handle_scope(env, scope) {
      return rt.call(true, () => {
        js.close_handle_scope(rt, scope >>> 0)
      })
    },

    js_open_escapable_handle_scope(env, result) {
      return rt.call(true, () => {
        const value = js.open_escapable_handle_scope(rt, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_close_escapable_handle_scope(env, scope) {
      return rt.call(true, () => {
        js.close_escapable_handle_scope(rt, scope >>> 0)
      })
    },

    js_escape_handle(env, scope, escapee, result) {
      return rt.call(true, () => {
        const value = js.escape_handle(rt, scope >>> 0, rt.value(escapee), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_context(env, result) {
      return rt.call(true, () => {
        const value = js.create_context(rt, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_destroy_context(env, context) {
      return rt.call(true, () => {
        js.destroy_context(rt, context >>> 0)
      })
    },

    js_enter_context(env, context) {
      return rt.call(true, () => {
        js.enter_context(rt, context >>> 0)
      })
    },

    js_exit_context(env, context) {
      return rt.call(true, () => {
        js.exit_context(rt, context >>> 0)
      })
    },

    js_get_bindings(env, result) {
      return rt.call(false, () => {
        const value = js.get_bindings(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_run_script(env, file, len, offset, source, result) {
      return rt.call(false, () => {
        const value = js.run_script(
          rt,
          rt.read.utf8(file, len >>> 0),
          len >>> 0,
          offset,
          rt.value(source),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_prepare_script(env, file, len, offset, source, result) {
      return rt.call(false, () => {
        const value = js.prepare_script(
          rt,
          rt.read.utf8(file, len >>> 0),
          len >>> 0,
          offset,
          rt.value(source),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_prepare_script_with_code_cache(
      env,
      file,
      len,
      offset,
      source,
      cached_data,
      cached_data_len,
      cache_rejected,
      result
    ) {
      return rt.call(false, () => {
        const values = js.prepare_script_with_code_cache(
          rt,
          rt.read.utf8(file, len >>> 0),
          len >>> 0,
          offset,
          rt.value(source),
          cached_data >>> 0,
          cached_data_len >>> 0,
          { cache_rejected: cache_rejected !== 0, result: result !== 0 }
        )
        if (cache_rejected !== 0) rt.write.bool(cache_rejected, values.cache_rejected)
        if (result !== 0) rt.write.u32(result, values.result)
      })
    },

    js_create_script_code_cache(env, script, data, len) {
      return rt.call(false, () => {
        const values = js.create_script_code_cache(rt, script >>> 0, {
          data: data !== 0,
          len: len !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
      })
    },

    js_run_prepared_script(env, script, result) {
      return rt.call(false, () => {
        const value = js.run_prepared_script(rt, script >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_delete_script(env, script) {
      return rt.call(true, () => {
        js.delete_script(rt, script >>> 0)
      })
    },

    js_get_script_name(env, script, result) {
      return rt.call(true, () => {
        const value = js.get_script_name(rt, script >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_script_id(env, script, result) {
      return rt.call(true, () => {
        const value = js.get_script_id(rt, script >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_on_script_dynamic_import(env, script, cb, data) {
      return rt.call(false, () => {
        js.on_script_dynamic_import(rt, script >>> 0, cb >>> 0, data >>> 0)
      })
    },

    js_create_module(env, name, len, offset, source, cb, data, result) {
      return rt.call(false, () => {
        const value = js.create_module(
          rt,
          rt.read.utf8(name, len >>> 0),
          len >>> 0,
          offset,
          rt.value(source),
          cb >>> 0,
          data >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_create_module_with_code_cache(
      env,
      name,
      len,
      offset,
      source,
      cached_data,
      cached_data_len,
      cache_rejected,
      cb,
      data,
      result
    ) {
      return rt.call(false, () => {
        const values = js.create_module_with_code_cache(
          rt,
          rt.read.utf8(name, len >>> 0),
          len >>> 0,
          offset,
          rt.value(source),
          cached_data >>> 0,
          cached_data_len >>> 0,
          cb >>> 0,
          data >>> 0,
          { cache_rejected: cache_rejected !== 0, result: result !== 0 }
        )
        if (cache_rejected !== 0) rt.write.bool(cache_rejected, values.cache_rejected)
        if (result !== 0) rt.write.u32(result, values.result)
      })
    },

    js_create_module_code_cache(env, module, data, len) {
      return rt.call(false, () => {
        const values = js.create_module_code_cache(rt, module >>> 0, {
          data: data !== 0,
          len: len !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
      })
    },

    js_create_synthetic_module(env, name, len, export_names, export_names_len, cb, data, result) {
      return rt.call(false, () => {
        const value = js.create_synthetic_module(
          rt,
          rt.read.utf8(name, len >>> 0),
          len >>> 0,
          rt.values(export_names, export_names_len >>> 0),
          export_names_len >>> 0,
          cb >>> 0,
          data >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_delete_module(env, module) {
      return rt.call(true, () => {
        js.delete_module(rt, module >>> 0)
      })
    },

    js_get_module_name(env, module, result) {
      return rt.call(true, () => {
        const value = js.get_module_name(rt, module >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_module_id(env, module, result) {
      return rt.call(true, () => {
        const value = js.get_module_id(rt, module >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_default_module_id(env, result) {
      return rt.call(true, () => {
        const value = js.get_default_module_id(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_module_namespace(env, module, result) {
      return rt.call(false, () => {
        const value = js.get_module_namespace(rt, module >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_set_module_export(env, module, name, value_) {
      return rt.call(false, () => {
        js.set_module_export(rt, module >>> 0, rt.value(name), rt.value(value_))
      })
    },

    js_instantiate_module(env, module, cb, data) {
      return rt.call(false, () => {
        js.instantiate_module(rt, module >>> 0, cb >>> 0, data >>> 0)
      })
    },

    js_run_module(env, module, result) {
      return rt.call(false, () => {
        const value = js.run_module(rt, module >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_on_module_dynamic_import(env, module, cb, data) {
      return rt.call(false, () => {
        js.on_module_dynamic_import(rt, module >>> 0, cb >>> 0, data >>> 0)
      })
    },

    js_create_reference(env, value_, count, result) {
      return rt.call(true, () => {
        const value = js.create_reference(rt, rt.value(value_), count >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_delete_reference(env, reference) {
      return rt.call(true, () => {
        js.delete_reference(rt, rt.ref(reference))
      })
    },

    js_reference_ref(env, reference, result) {
      return rt.call(true, () => {
        const value = js.reference_ref(rt, rt.ref(reference), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_reference_unref(env, reference, result) {
      return rt.call(true, () => {
        const value = js.reference_unref(rt, rt.ref(reference), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_reference_value(env, reference, result) {
      return rt.call(true, () => {
        const value = js.get_reference_value(rt, rt.ref(reference), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_define_class(env, name, len, constructor, data, properties, properties_len, result) {
      return rt.call(false, () => {
        const value = js.define_class(
          rt,
          rt.read.utf8(name, len >>> 0),
          len >>> 0,
          constructor >>> 0,
          data >>> 0,
          properties >>> 0,
          properties_len >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_define_properties(env, object, properties, properties_len) {
      return rt.call(false, () => {
        js.define_properties(rt, rt.value(object), properties >>> 0, properties_len >>> 0)
      })
    },

    js_wrap(env, object, data, finalize_cb, finalize_hint, result) {
      return rt.call(false, () => {
        const value = js.wrap(
          rt,
          rt.value(object),
          data >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_unwrap(env, object, result) {
      return rt.call(false, () => {
        const value = js.unwrap(rt, rt.value(object), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_remove_wrap(env, object, result) {
      return rt.call(false, () => {
        const value = js.remove_wrap(rt, rt.value(object), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_create_delegate(env, callbacks, data, finalize_cb, finalize_hint, result) {
      return rt.call(false, () => {
        const value = js.create_delegate(
          rt,
          callbacks >>> 0,
          data >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_add_finalizer(env, object, data, finalize_cb, finalize_hint, result) {
      return rt.call(true, () => {
        const value = js.add_finalizer(
          rt,
          rt.value(object),
          data >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_add_type_tag(env, object, tag) {
      return rt.call(false, () => {
        js.add_type_tag(rt, rt.value(object), tag >>> 0)
      })
    },

    js_check_type_tag(env, object, tag, result) {
      return rt.call(false, () => {
        const value = js.check_type_tag(rt, rt.value(object), tag >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_create_int32(env, value_, result) {
      return rt.call(true, () => {
        const value = js.create_int32(rt, value_, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_uint32(env, value_, result) {
      return rt.call(true, () => {
        const value = js.create_uint32(rt, value_ >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_int64(env, value_, result) {
      return rt.call(true, () => {
        const value = js.create_int64(rt, value_, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_double(env, value_, result) {
      return rt.call(true, () => {
        const value = js.create_double(rt, value_, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_bigint_int64(env, value_, result) {
      return rt.call(true, () => {
        const value = js.create_bigint_int64(rt, value_, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_bigint_uint64(env, value_, result) {
      return rt.call(true, () => {
        const value = js.create_bigint_uint64(rt, BigInt.asUintN(64, value_), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_bigint_words(env, sign, words, len, result) {
      return rt.call(false, () => {
        const value = js.create_bigint_words(rt, sign, words >>> 0, len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_string_utf8(env, str, len, result) {
      return rt.call(false, () => {
        const value = js.create_string_utf8(rt, rt.read.utf8(str, len >>> 0), len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_string_utf16le(env, str, len, result) {
      return rt.call(false, () => {
        const value = js.create_string_utf16le(rt, rt.read.utf16le(str, len >>> 0), len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_string_latin1(env, str, len, result) {
      return rt.call(false, () => {
        const value = js.create_string_latin1(rt, rt.read.latin1(str, len >>> 0), len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_external_string_utf8(env, str, len, finalize_cb, finalize_hint, result, copied) {
      return rt.call(false, () => {
        const values = js.create_external_string_utf8(
          rt,
          str >>> 0,
          len >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0, copied: copied !== 0 }
        )
        if (result !== 0) rt.write.value(result, values.result)
        if (copied !== 0) rt.write.bool(copied, values.copied)
      })
    },

    js_create_external_string_utf16le(env, str, len, finalize_cb, finalize_hint, result, copied) {
      return rt.call(false, () => {
        const values = js.create_external_string_utf16le(
          rt,
          str >>> 0,
          len >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0, copied: copied !== 0 }
        )
        if (result !== 0) rt.write.value(result, values.result)
        if (copied !== 0) rt.write.bool(copied, values.copied)
      })
    },

    js_create_external_string_latin1(env, str, len, finalize_cb, finalize_hint, result, copied) {
      return rt.call(false, () => {
        const values = js.create_external_string_latin1(
          rt,
          str >>> 0,
          len >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0, copied: copied !== 0 }
        )
        if (result !== 0) rt.write.value(result, values.result)
        if (copied !== 0) rt.write.bool(copied, values.copied)
      })
    },

    js_create_property_key_utf8(env, str, len, result) {
      return rt.call(false, () => {
        const value = js.create_property_key_utf8(rt, rt.read.utf8(str, len >>> 0), len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_property_key_utf16le(env, str, len, result) {
      return rt.call(false, () => {
        const value = js.create_property_key_utf16le(
          rt,
          rt.read.utf16le(str, len >>> 0),
          len >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_property_key_latin1(env, str, len, result) {
      return rt.call(false, () => {
        const value = js.create_property_key_latin1(rt, rt.read.latin1(str, len >>> 0), len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_symbol(env, description, result) {
      return rt.call(true, () => {
        const value = js.create_symbol(rt, rt.value(description), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_symbol_for(env, description, len, result) {
      return rt.call(false, () => {
        const value = js.symbol_for(rt, rt.read.utf8(description, len >>> 0), len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_object(env, result) {
      return rt.call(true, () => {
        const value = js.create_object(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_object_with_prototype(env, prototype, result) {
      return rt.call(true, () => {
        const value = js.create_object_with_prototype(rt, rt.value(prototype), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_object_with_properties(
      env,
      prototype,
      property_names,
      property_values,
      property_count,
      result
    ) {
      return rt.call(true, () => {
        const value = js.create_object_with_properties(
          rt,
          rt.value(prototype),
          rt.values(property_names, property_count >>> 0),
          rt.values(property_values, property_count >>> 0),
          property_count >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_function(env, name, len, cb, data, result) {
      return rt.call(false, () => {
        const value = js.create_function(
          rt,
          rt.read.utf8(name, len >>> 0),
          len >>> 0,
          cb >>> 0,
          data >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_compile_function(
      env,
      name,
      name_len,
      file,
      file_len,
      args,
      args_len,
      offset,
      source,
      result
    ) {
      return rt.call(false, () => {
        const value = js.compile_function(
          rt,
          rt.read.utf8(name, name_len >>> 0),
          name_len >>> 0,
          rt.read.utf8(file, file_len >>> 0),
          file_len >>> 0,
          rt.values(args, args_len >>> 0),
          args_len >>> 0,
          offset,
          rt.value(source),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_compile_function_with_code_cache(
      env,
      name,
      name_len,
      file,
      file_len,
      args,
      args_len,
      offset,
      source,
      cached_data,
      cached_data_len,
      cache_rejected,
      result
    ) {
      return rt.call(false, () => {
        const values = js.compile_function_with_code_cache(
          rt,
          rt.read.utf8(name, name_len >>> 0),
          name_len >>> 0,
          rt.read.utf8(file, file_len >>> 0),
          file_len >>> 0,
          rt.values(args, args_len >>> 0),
          args_len >>> 0,
          offset,
          rt.value(source),
          cached_data >>> 0,
          cached_data_len >>> 0,
          { cache_rejected: cache_rejected !== 0, result: result !== 0 }
        )
        if (cache_rejected !== 0) rt.write.bool(cache_rejected, values.cache_rejected)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_function_code_cache(env, function_, data, len) {
      return rt.call(false, () => {
        const values = js.create_function_code_cache(rt, rt.value(function_), {
          data: data !== 0,
          len: len !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
      })
    },

    js_create_function_with_source(
      env,
      name,
      name_len,
      file,
      file_len,
      args,
      args_len,
      offset,
      source,
      result
    ) {
      return rt.call(false, () => {
        const value = js.create_function_with_source(
          rt,
          rt.read.utf8(name, name_len >>> 0),
          name_len >>> 0,
          rt.read.utf8(file, file_len >>> 0),
          file_len >>> 0,
          rt.values(args, args_len >>> 0),
          args_len >>> 0,
          offset,
          rt.value(source),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_typed_function(env, name, len, cb, signature, address, data, result) {
      return rt.call(false, () => {
        const value = js.create_typed_function(
          rt,
          rt.read.utf8(name, len >>> 0),
          len >>> 0,
          cb >>> 0,
          signature >>> 0,
          address >>> 0,
          data >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_function_id(env, function_, result) {
      return rt.call(true, () => {
        const value = js.get_function_id(rt, rt.value(function_), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_on_function_dynamic_import(env, function_, cb, data) {
      return rt.call(false, () => {
        js.on_function_dynamic_import(rt, rt.value(function_), cb >>> 0, data >>> 0)
      })
    },

    js_create_array(env, result) {
      return rt.call(true, () => {
        const value = js.create_array(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_array_with_length(env, len, result) {
      return rt.call(false, () => {
        const value = js.create_array_with_length(rt, len >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_array_with_elements(env, elements, element_count, result) {
      return rt.call(true, () => {
        const value = js.create_array_with_elements(
          rt,
          rt.values(elements, element_count >>> 0),
          element_count >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_external(env, data, finalize_cb, finalize_hint, result) {
      return rt.call(true, () => {
        const value = js.create_external(rt, data >>> 0, finalize_cb >>> 0, finalize_hint >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_date(env, time, result) {
      return rt.call(true, () => {
        const value = js.create_date(rt, time, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_error(env, code, message, result) {
      return rt.call(true, () => {
        const value = js.create_error(rt, rt.value(code), rt.value(message), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_type_error(env, code, message, result) {
      return rt.call(true, () => {
        const value = js.create_type_error(rt, rt.value(code), rt.value(message), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_range_error(env, code, message, result) {
      return rt.call(true, () => {
        const value = js.create_range_error(rt, rt.value(code), rt.value(message), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_syntax_error(env, code, message, result) {
      return rt.call(true, () => {
        const value = js.create_syntax_error(rt, rt.value(code), rt.value(message), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_reference_error(env, code, message, result) {
      return rt.call(true, () => {
        const value = js.create_reference_error(rt, rt.value(code), rt.value(message), {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_error_location(env, error, result) {
      return rt.call(true, () => {
        js.get_error_location(rt, rt.value(error), result >>> 0)
      })
    },

    js_create_promise(env, deferred, promise) {
      return rt.call(true, () => {
        const values = js.create_promise(rt, { deferred: deferred !== 0, promise: promise !== 0 })
        if (deferred !== 0) rt.write.u32(deferred, values.deferred)
        if (promise !== 0) rt.write.value(promise, values.promise)
      })
    },

    js_resolve_deferred(env, deferred, resolution) {
      return rt.call(true, () => {
        js.resolve_deferred(rt, deferred >>> 0, rt.value(resolution))
      })
    },

    js_reject_deferred(env, deferred, resolution) {
      return rt.call(true, () => {
        js.reject_deferred(rt, deferred >>> 0, rt.value(resolution))
      })
    },

    js_get_promise_state(env, promise, result) {
      return rt.call(true, () => {
        const value = js.get_promise_state(rt, rt.value(promise), { result: result !== 0 })
        if (result !== 0) rt.write.i32(result, value)
      })
    },

    js_get_promise_result(env, promise, result) {
      return rt.call(true, () => {
        const value = js.get_promise_result(rt, rt.value(promise), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_arraybuffer(env, len, data, result) {
      return rt.call(false, () => {
        const values = js.create_arraybuffer(rt, len >>> 0, {
          data: data !== 0,
          result: result !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_arraybuffer_with_backing_store(env, backing_store, data, len, result) {
      return rt.call(false, () => {
        const values = js.create_arraybuffer_with_backing_store(rt, backing_store >>> 0, {
          data: data !== 0,
          len: len !== 0,
          result: result !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_unsafe_arraybuffer(env, len, data, result) {
      return rt.call(false, () => {
        const values = js.create_unsafe_arraybuffer(rt, len >>> 0, {
          data: data !== 0,
          result: result !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_external_arraybuffer(env, data, len, finalize_cb, finalize_hint, result) {
      return rt.call(false, () => {
        const value = js.create_external_arraybuffer(
          rt,
          data >>> 0,
          len >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_detach_arraybuffer(env, arraybuffer) {
      return rt.call(true, () => {
        js.detach_arraybuffer(rt, rt.value(arraybuffer))
      })
    },

    js_get_arraybuffer_backing_store(env, arraybuffer, result) {
      return rt.call(true, () => {
        const value = js.get_arraybuffer_backing_store(rt, rt.value(arraybuffer), {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_create_sharedarraybuffer(env, len, data, result) {
      return rt.call(false, () => {
        const values = js.create_sharedarraybuffer(rt, len >>> 0, {
          data: data !== 0,
          result: result !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_sharedarraybuffer_with_backing_store(env, backing_store, data, len, result) {
      return rt.call(false, () => {
        const values = js.create_sharedarraybuffer_with_backing_store(rt, backing_store >>> 0, {
          data: data !== 0,
          len: len !== 0,
          result: result !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_unsafe_sharedarraybuffer(env, len, data, result) {
      return rt.call(false, () => {
        const values = js.create_unsafe_sharedarraybuffer(rt, len >>> 0, {
          data: data !== 0,
          result: result !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (result !== 0) rt.write.value(result, values.result)
      })
    },

    js_create_external_sharedarraybuffer(env, data, len, finalize_cb, finalize_hint, result) {
      return rt.call(false, () => {
        const value = js.create_external_sharedarraybuffer(
          rt,
          data >>> 0,
          len >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_sharedarraybuffer_backing_store(env, sharedarraybuffer, result) {
      return rt.call(true, () => {
        const value = js.get_sharedarraybuffer_backing_store(rt, rt.value(sharedarraybuffer), {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_release_arraybuffer_backing_store(env, backing_store) {
      return rt.call(true, () => {
        js.release_arraybuffer_backing_store(rt, backing_store >>> 0)
      })
    },

    js_create_typedarray(env, type, len, arraybuffer, offset, result) {
      return rt.call(false, () => {
        const value = js.create_typedarray(
          rt,
          type,
          len >>> 0,
          rt.value(arraybuffer),
          offset >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_dataview(env, len, arraybuffer, offset, result) {
      return rt.call(false, () => {
        const value = js.create_dataview(rt, len >>> 0, rt.value(arraybuffer), offset >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_coerce_to_boolean(env, value_, result) {
      return rt.call(true, () => {
        const value = js.coerce_to_boolean(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_coerce_to_number(env, value_, result) {
      return rt.call(false, () => {
        const value = js.coerce_to_number(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_coerce_to_string(env, value_, result) {
      return rt.call(false, () => {
        const value = js.coerce_to_string(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_coerce_to_object(env, value_, result) {
      return rt.call(false, () => {
        const value = js.coerce_to_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_typeof(env, value_, result) {
      return rt.call(true, () => {
        const value = js.typeof(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.i32(result, value)
      })
    },

    js_instanceof(env, object, constructor, result) {
      return rt.call(false, () => {
        const value = js.instanceof(rt, rt.value(object), rt.value(constructor), {
          result: result !== 0
        })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_undefined(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_undefined(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_null(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_null(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_boolean(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_boolean(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_boolean_object(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_boolean_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_number(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_number(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_number_object(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_number_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_int32(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_int32(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_uint32(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_uint32(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_string(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_string(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_string_object(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_string_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_symbol(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_symbol(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_symbol_object(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_symbol_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_object(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_function(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_function(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_async_function(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_async_function(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_generator_function(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_generator_function(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_generator(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_generator(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_arguments(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_arguments(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_external(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_external(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_wrapped(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_wrapped(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_delegate(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_delegate(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_bigint(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_bigint(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_bigint_object(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_bigint_object(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_date(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_date(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_regexp(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_regexp(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_error(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_error(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_promise(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_promise(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_proxy(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_proxy(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_map(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_map(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_map_iterator(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_map_iterator(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_set(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_set(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_set_iterator(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_set_iterator(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_weak_map(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_weak_map(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_weak_set(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_weak_set(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_weak_ref(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_weak_ref(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_arraybuffer(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_arraybuffer(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_detached_arraybuffer(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_detached_arraybuffer(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_sharedarraybuffer(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_sharedarraybuffer(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_typedarray(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_typedarray(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_int8array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_int8array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_uint8array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_uint8array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_uint8clampedarray(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_uint8clampedarray(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_int16array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_int16array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_uint16array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_uint16array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_int32array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_int32array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_uint32array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_uint32array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_float16array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_float16array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_float32array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_float32array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_float64array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_float64array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_bigint64array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_bigint64array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_biguint64array(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_biguint64array(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_dataview(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_dataview(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_is_module_namespace(env, value_, result) {
      return rt.call(true, () => {
        const value = js.is_module_namespace(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_object_type(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_object_type(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.i32(result, value)
      })
    },

    js_strict_equals(env, a, b, result) {
      return rt.call(true, () => {
        const value = js.strict_equals(rt, rt.value(a), rt.value(b), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_global(env, result) {
      return rt.call(true, () => {
        const value = js.get_global(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_undefined(env, result) {
      return rt.call(true, () => {
        const value = js.get_undefined(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_null(env, result) {
      return rt.call(true, () => {
        const value = js.get_null(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_boolean(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_boolean(rt, value_ !== 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_value_bool(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_bool(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_value_int32(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_int32(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.i32(result, value)
      })
    },

    js_get_value_uint32(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_uint32(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_value_int64(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_int64(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.i64(result, value)
      })
    },

    js_get_value_double(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_double(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.f64(result, value)
      })
    },

    js_get_value_bigint_int64(env, value_, result, lossless) {
      return rt.call(true, () => {
        const values = js.get_value_bigint_int64(rt, rt.value(value_), {
          result: result !== 0,
          lossless: lossless !== 0
        })
        if (result !== 0) rt.write.i64(result, values.result)
        if (lossless !== 0) rt.write.bool(lossless, values.lossless)
      })
    },

    js_get_value_bigint_uint64(env, value_, result, lossless) {
      return rt.call(true, () => {
        const values = js.get_value_bigint_uint64(rt, rt.value(value_), {
          result: result !== 0,
          lossless: lossless !== 0
        })
        if (result !== 0) rt.write.u64(result, values.result)
        if (lossless !== 0) rt.write.bool(lossless, values.lossless)
      })
    },

    js_get_value_bigint_words(env, value_, sign, words, len, result) {
      return rt.call(true, () => {
        const values = js.get_value_bigint_words(rt, rt.value(value_), words >>> 0, len >>> 0, {
          sign: sign !== 0,
          result: result !== 0
        })
        if (sign !== 0) rt.write.i32(sign, values.sign)
        if (result !== 0) rt.write.u32(result, values.result)
      })
    },

    js_get_value_string_utf8(env, value_, str, len, result) {
      return rt.call(true, () => {
        const value = js.get_value_string_utf8(rt, rt.value(value_), str >>> 0, len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_value_string_utf16le(env, value_, str, len, result) {
      return rt.call(true, () => {
        const value = js.get_value_string_utf16le(rt, rt.value(value_), str >>> 0, len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_value_string_latin1(env, value_, str, len, result) {
      return rt.call(true, () => {
        const value = js.get_value_string_latin1(rt, rt.value(value_), str >>> 0, len >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_value_external(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_external(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_value_date(env, value_, result) {
      return rt.call(true, () => {
        const value = js.get_value_date(rt, rt.value(value_), { result: result !== 0 })
        if (result !== 0) rt.write.f64(result, value)
      })
    },

    js_get_array_length(env, array, result) {
      return rt.call(true, () => {
        const value = js.get_array_length(rt, rt.value(array), { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_array_elements(env, array, elements, len, offset, result) {
      return rt.call(false, () => {
        const value = js.get_array_elements(
          rt,
          rt.value(array),
          elements >>> 0,
          len >>> 0,
          offset >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_set_array_elements(env, array, elements, len, offset) {
      return rt.call(false, () => {
        js.set_array_elements(
          rt,
          rt.value(array),
          rt.values(elements, len >>> 0),
          len >>> 0,
          offset >>> 0
        )
      })
    },

    js_get_prototype(env, object, result) {
      return rt.call(true, () => {
        const value = js.get_prototype(rt, rt.value(object), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_set_prototype(env, object, prototype) {
      return rt.call(false, () => {
        js.set_prototype(rt, rt.value(object), rt.value(prototype))
      })
    },

    js_seal(env, object) {
      return rt.call(false, () => {
        js.seal(rt, rt.value(object))
      })
    },

    js_freeze(env, object) {
      return rt.call(false, () => {
        js.freeze(rt, rt.value(object))
      })
    },

    js_get_property_names(env, object, result) {
      return rt.call(false, () => {
        const value = js.get_property_names(rt, rt.value(object), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_filtered_property_names(
      env,
      object,
      mode,
      property_filter,
      index_filter,
      key_conversion,
      result
    ) {
      return rt.call(false, () => {
        const value = js.get_filtered_property_names(
          rt,
          rt.value(object),
          mode,
          property_filter,
          index_filter,
          key_conversion,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_property(env, object, key, result) {
      return rt.call(false, () => {
        const value = js.get_property(rt, rt.value(object), rt.value(key), { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_has_property(env, object, key, result) {
      return rt.call(false, () => {
        const value = js.has_property(rt, rt.value(object), rt.value(key), { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_has_own_property(env, object, key, result) {
      return rt.call(false, () => {
        const value = js.has_own_property(rt, rt.value(object), rt.value(key), {
          result: result !== 0
        })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_set_property(env, object, key, value_) {
      return rt.call(false, () => {
        js.set_property(rt, rt.value(object), rt.value(key), rt.value(value_))
      })
    },

    js_delete_property(env, object, key, result) {
      return rt.call(false, () => {
        const value = js.delete_property(rt, rt.value(object), rt.value(key), {
          result: result !== 0
        })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_named_property(env, object, name, result) {
      return rt.call(false, () => {
        const value = js.get_named_property(
          rt,
          rt.value(object),
          rt.read.utf8(name, rt.NUL_TERMINATED),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_has_named_property(env, object, name, result) {
      return rt.call(false, () => {
        const value = js.has_named_property(
          rt,
          rt.value(object),
          rt.read.utf8(name, rt.NUL_TERMINATED),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_set_named_property(env, object, name, value_) {
      return rt.call(false, () => {
        js.set_named_property(
          rt,
          rt.value(object),
          rt.read.utf8(name, rt.NUL_TERMINATED),
          rt.value(value_)
        )
      })
    },

    js_delete_named_property(env, object, name, result) {
      return rt.call(false, () => {
        const value = js.delete_named_property(
          rt,
          rt.value(object),
          rt.read.utf8(name, rt.NUL_TERMINATED),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_element(env, object, index, result) {
      return rt.call(false, () => {
        const value = js.get_element(rt, rt.value(object), index >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_has_element(env, object, index, result) {
      return rt.call(false, () => {
        const value = js.has_element(rt, rt.value(object), index >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_set_element(env, object, index, value_) {
      return rt.call(false, () => {
        js.set_element(rt, rt.value(object), index >>> 0, rt.value(value_))
      })
    },

    js_delete_element(env, object, index, result) {
      return rt.call(false, () => {
        const value = js.delete_element(rt, rt.value(object), index >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_string_view(env, string, encoding, str, len, result) {
      return rt.call(true, () => {
        const values = js.get_string_view(rt, rt.value(string), {
          encoding: encoding !== 0,
          str: str !== 0,
          len: len !== 0,
          result: result !== 0
        })
        if (encoding !== 0) rt.write.i32(encoding, values.encoding)
        if (str !== 0) rt.write.u32(str, values.str)
        if (len !== 0) rt.write.u32(len, values.len)
        if (result !== 0) rt.write.u32(result, values.result)
      })
    },

    js_release_string_view(env, view) {
      return rt.call(true, () => {
        js.release_string_view(rt, view >>> 0)
      })
    },

    js_get_callback_info(env, info, argc, argv, receiver, data) {
      return rt.call(true, () => {
        const values = js.get_callback_info(rt, info >>> 0, argc >>> 0, argv >>> 0, {
          receiver: receiver !== 0,
          data: data !== 0
        })
        if (receiver !== 0) rt.write.value(receiver, values.receiver)
        if (data !== 0) rt.write.u32(data, values.data)
      })
    },

    js_get_typed_callback_info(info, env, data) {
      return rt.call(true, () => {
        const values = js.get_typed_callback_info(rt, info >>> 0, {
          env: env !== 0,
          data: data !== 0
        })
        if (env !== 0) rt.write.u32(env, values.env)
        if (data !== 0) rt.write.u32(data, values.data)
      })
    },

    js_get_new_target(env, info, result) {
      return rt.call(true, () => {
        const value = js.get_new_target(rt, info >>> 0, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_get_arraybuffer_info(env, arraybuffer, data, len) {
      return rt.call(true, () => {
        const values = js.get_arraybuffer_info(rt, rt.value(arraybuffer), {
          data: data !== 0,
          len: len !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
      })
    },

    js_get_sharedarraybuffer_info(env, sharedarraybuffer, data, len) {
      return rt.call(true, () => {
        const values = js.get_sharedarraybuffer_info(rt, rt.value(sharedarraybuffer), {
          data: data !== 0,
          len: len !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
      })
    },

    js_get_typedarray_info(env, typedarray, type, data, len, arraybuffer, offset) {
      return rt.call(true, () => {
        const values = js.get_typedarray_info(rt, rt.value(typedarray), {
          type: type !== 0,
          data: data !== 0,
          len: len !== 0,
          arraybuffer: arraybuffer !== 0,
          offset: offset !== 0
        })
        if (type !== 0) rt.write.i32(type, values.type)
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
        if (arraybuffer !== 0) rt.write.value(arraybuffer, values.arraybuffer)
        if (offset !== 0) rt.write.u32(offset, values.offset)
      })
    },

    js_get_dataview_info(env, dataview, data, len, arraybuffer, offset) {
      return rt.call(true, () => {
        const values = js.get_dataview_info(rt, rt.value(dataview), {
          data: data !== 0,
          len: len !== 0,
          arraybuffer: arraybuffer !== 0,
          offset: offset !== 0
        })
        if (data !== 0) rt.write.u32(data, values.data)
        if (len !== 0) rt.write.u32(len, values.len)
        if (arraybuffer !== 0) rt.write.value(arraybuffer, values.arraybuffer)
        if (offset !== 0) rt.write.u32(offset, values.offset)
      })
    },

    js_call_function(env, receiver, function_, argc, argv, result) {
      return rt.call(false, () => {
        const value = js.call_function(
          rt,
          rt.value(receiver),
          rt.value(function_),
          argc >>> 0,
          rt.values(argv, argc >>> 0),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_call_function_with_checkpoint(env, receiver, function_, argc, argv, result) {
      return rt.call(false, () => {
        const value = js.call_function_with_checkpoint(
          rt,
          rt.value(receiver),
          rt.value(function_),
          argc >>> 0,
          rt.values(argv, argc >>> 0),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_queue_microtask(env, function_) {
      return rt.call(true, () => {
        js.queue_microtask(rt, rt.value(function_))
      })
    },

    js_queue_microtask_with_callback(env, cb, data) {
      return rt.call(true, () => {
        js.queue_microtask_with_callback(rt, cb >>> 0, data >>> 0)
      })
    },

    js_new_instance(env, constructor, argc, argv, result) {
      return rt.call(false, () => {
        const value = js.new_instance(
          rt,
          rt.value(constructor),
          argc >>> 0,
          rt.values(argv, argc >>> 0),
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_create_threadsafe_function(
      env,
      function_,
      queue_limit,
      initial_thread_count,
      finalize_cb,
      finalize_hint,
      context,
      cb,
      result
    ) {
      return rt.call(false, () => {
        const value = js.create_threadsafe_function(
          rt,
          rt.value(function_),
          queue_limit >>> 0,
          initial_thread_count >>> 0,
          finalize_cb >>> 0,
          finalize_hint >>> 0,
          context >>> 0,
          cb >>> 0,
          { result: result !== 0 }
        )
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_get_threadsafe_function_context(function_, result) {
      return rt.call(true, () => {
        const value = js.get_threadsafe_function_context(rt, function_ >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_call_threadsafe_function(function_, data, mode) {
      return rt.call(true, () => {
        js.call_threadsafe_function(rt, function_ >>> 0, data >>> 0, mode)
      })
    },

    js_acquire_threadsafe_function(function_) {
      return rt.call(true, () => {
        js.acquire_threadsafe_function(rt, function_ >>> 0)
      })
    },

    js_release_threadsafe_function(function_, mode) {
      return rt.call(true, () => {
        js.release_threadsafe_function(rt, function_ >>> 0, mode)
      })
    },

    js_ref_threadsafe_function(env, function_) {
      return rt.call(true, () => {
        js.ref_threadsafe_function(rt, function_ >>> 0)
      })
    },

    js_unref_threadsafe_function(env, function_) {
      return rt.call(true, () => {
        js.unref_threadsafe_function(rt, function_ >>> 0)
      })
    },

    js_add_teardown_callback(env, callback, data) {
      return rt.call(false, () => {
        js.add_teardown_callback(rt, callback >>> 0, data >>> 0)
      })
    },

    js_remove_teardown_callback(env, callback, data) {
      return rt.call(false, () => {
        js.remove_teardown_callback(rt, callback >>> 0, data >>> 0)
      })
    },

    js_add_deferred_teardown_callback(env, callback, data, result) {
      return rt.call(false, () => {
        const value = js.add_deferred_teardown_callback(rt, callback >>> 0, data >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_finish_deferred_teardown_callback(handle) {
      return rt.call(true, () => {
        js.finish_deferred_teardown_callback(rt, handle >>> 0)
      })
    },

    js_throw(env, error) {
      return rt.call(false, () => {
        js.throw(rt, rt.value(error))
      })
    },

    js_throw_error(env, code, message) {
      return rt.call(false, () => {
        js.throw_error(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED)
        )
      })
    },

    js_throw_verrorf(env, code, message, args) {
      return rt.call(false, () => {
        js.throw_verrorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          args >>> 0
        )
      })
    },

    js_throw_errorf(env, code, message, varargs) {
      return rt.call(false, () => {
        js.throw_errorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          varargs >>> 0
        )
      })
    },

    js_throw_type_error(env, code, message) {
      return rt.call(false, () => {
        js.throw_type_error(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED)
        )
      })
    },

    js_throw_type_verrorf(env, code, message, args) {
      return rt.call(false, () => {
        js.throw_type_verrorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          args >>> 0
        )
      })
    },

    js_throw_type_errorf(env, code, message, varargs) {
      return rt.call(false, () => {
        js.throw_type_errorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          varargs >>> 0
        )
      })
    },

    js_throw_range_error(env, code, message) {
      return rt.call(false, () => {
        js.throw_range_error(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED)
        )
      })
    },

    js_throw_range_verrorf(env, code, message, args) {
      return rt.call(false, () => {
        js.throw_range_verrorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          args >>> 0
        )
      })
    },

    js_throw_range_errorf(env, code, message, varargs) {
      return rt.call(false, () => {
        js.throw_range_errorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          varargs >>> 0
        )
      })
    },

    js_throw_syntax_error(env, code, message) {
      return rt.call(false, () => {
        js.throw_syntax_error(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED)
        )
      })
    },

    js_throw_syntax_verrorf(env, code, message, args) {
      return rt.call(false, () => {
        js.throw_syntax_verrorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          args >>> 0
        )
      })
    },

    js_throw_syntax_errorf(env, code, message, varargs) {
      return rt.call(false, () => {
        js.throw_syntax_errorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          varargs >>> 0
        )
      })
    },

    js_throw_reference_error(env, code, message) {
      return rt.call(false, () => {
        js.throw_reference_error(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED)
        )
      })
    },

    js_throw_reference_verrorf(env, code, message, args) {
      return rt.call(false, () => {
        js.throw_reference_verrorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          args >>> 0
        )
      })
    },

    js_throw_reference_errorf(env, code, message, varargs) {
      return rt.call(false, () => {
        js.throw_reference_errorf(
          rt,
          rt.read.utf8(code, rt.NUL_TERMINATED),
          rt.read.utf8(message, rt.NUL_TERMINATED),
          varargs >>> 0
        )
      })
    },

    js_is_exception_pending(env, result) {
      return rt.call(true, () => {
        const value = js.is_exception_pending(rt, { result: result !== 0 })
        if (result !== 0) rt.write.bool(result, value)
      })
    },

    js_get_and_clear_last_exception(env, result) {
      return rt.call(true, () => {
        const value = js.get_and_clear_last_exception(rt, { result: result !== 0 })
        if (result !== 0) rt.write.value(result, value)
      })
    },

    js_fatal_exception(env, error) {
      return rt.call(true, () => {
        js.fatal_exception(rt, rt.value(error))
      })
    },

    js_terminate_execution(env) {
      return rt.call(true, () => {
        js.terminate_execution(rt)
      })
    },

    js_adjust_external_memory(env, change_in_bytes, result) {
      return rt.call(true, () => {
        const value = js.adjust_external_memory(rt, change_in_bytes, { result: result !== 0 })
        if (result !== 0) rt.write.i64(result, value)
      })
    },

    js_request_garbage_collection(env) {
      return rt.call(true, () => {
        js.request_garbage_collection(rt)
      })
    },

    js_enable_garbage_collection_tracking(env, options, data, result) {
      return rt.call(true, () => {
        const value = js.enable_garbage_collection_tracking(rt, options >>> 0, data >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_disable_garbage_collection_tracking(env, tracking) {
      return rt.call(true, () => {
        js.disable_garbage_collection_tracking(rt, tracking >>> 0)
      })
    },

    js_get_heap_statistics(env, result) {
      return rt.call(true, () => {
        js.get_heap_statistics(rt, result >>> 0)
      })
    },

    js_get_heap_space_statistics(env, statistics, len, offset, result) {
      return rt.call(true, () => {
        const value = js.get_heap_space_statistics(rt, statistics >>> 0, len >>> 0, offset >>> 0, {
          result: result !== 0
        })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_create_inspector(env, result) {
      return rt.call(false, () => {
        const value = js.create_inspector(rt, { result: result !== 0 })
        if (result !== 0) rt.write.u32(result, value)
      })
    },

    js_destroy_inspector(env, inspector) {
      return rt.call(false, () => {
        js.destroy_inspector(rt, inspector >>> 0)
      })
    },

    js_on_inspector_response(env, inspector, cb, data) {
      return rt.call(false, () => {
        js.on_inspector_response(rt, inspector >>> 0, cb >>> 0, data >>> 0)
      })
    },

    js_on_inspector_paused(env, inspector, cb, data) {
      return rt.call(false, () => {
        js.on_inspector_paused(rt, inspector >>> 0, cb >>> 0, data >>> 0)
      })
    },

    js_connect_inspector(env, inspector) {
      return rt.call(false, () => {
        js.connect_inspector(rt, inspector >>> 0)
      })
    },

    js_send_inspector_request(env, inspector, message, len) {
      return rt.call(false, () => {
        js.send_inspector_request(rt, inspector >>> 0, rt.read.utf8(message, len >>> 0), len >>> 0)
      })
    },

    js_attach_context_to_inspector(env, inspector, context, name, len) {
      return rt.call(false, () => {
        js.attach_context_to_inspector(
          rt,
          inspector >>> 0,
          context >>> 0,
          rt.read.utf8(name, len >>> 0),
          len >>> 0
        )
      })
    },

    js_detach_context_from_inspector(env, inspector, context) {
      return rt.call(false, () => {
        js.detach_context_from_inspector(rt, inspector >>> 0, context >>> 0)
      })
    }
  }
}
