// Generated by scripts/generate.js from js.h for wasm32. Do not edit.

exports.enums = {
  js_pending_exception: -1,
  js_uncaught_exception: -2,
  js_undefined: 0,
  js_null: 1,
  js_boolean: 2,
  js_number: 3,
  js_string: 4,
  js_symbol: 5,
  js_object: 6,
  js_function: 7,
  js_external: 8,
  js_bigint: 9,
  js_array: 262,
  js_arguments: 518,
  js_date: 774,
  js_regexp: 1030,
  js_error: 1286,
  js_promise: 1542,
  js_proxy: 1798,
  js_generator: 2054,
  js_map: 2310,
  js_set: 2566,
  js_map_iterator: 2822,
  js_set_iterator: 3078,
  js_weak_map: 3334,
  js_weak_set: 3590,
  js_weak_ref: 3846,
  js_arraybuffer: 4102,
  js_sharedarraybuffer: 4358,
  js_typedarray: 4614,
  js_dataview: 4870,
  js_module_namespace: 5126,
  js_boolean_object: 5382,
  js_number_object: 5638,
  js_string_object: 5894,
  js_symbol_object: 6150,
  js_bigint_object: 6406,
  js_int8array: 0,
  js_uint8array: 1,
  js_uint8clampedarray: 2,
  js_int16array: 3,
  js_uint16array: 4,
  js_int32array: 5,
  js_uint32array: 6,
  js_float16array: 11,
  js_float32array: 7,
  js_float64array: 8,
  js_bigint64array: 9,
  js_biguint64array: 10,
  js_int8: 259,
  js_uint8: 515,
  js_int16: 771,
  js_uint16: 1027,
  js_int32: 1283,
  js_uint32: 1539,
  js_int64: 1795,
  js_uint64: 2051,
  js_float16: 2819,
  js_float32: 2307,
  js_float64: 2563,
  js_bigint64: 265,
  js_biguint64: 521,
  js_promise_pending: 0,
  js_promise_fulfilled: 1,
  js_promise_rejected: 2,
  js_writable: 1,
  js_enumerable: 2,
  js_configurable: 4,
  js_static: 1024,
  js_key_include_prototypes: 0,
  js_key_own_only: 1,
  js_key_convert_to_string: 0,
  js_key_keep_numbers: 1,
  js_property_all_properties: 0,
  js_property_only_writable: 1,
  js_property_only_enumerable: 2,
  js_property_only_configurable: 4,
  js_property_skip_strings: 8,
  js_property_skip_symbols: 16,
  js_index_include_indices: 0,
  js_index_skip_indices: 1,
  js_utf8: 1,
  js_utf16le: 2,
  js_latin1: 3,
  js_threadsafe_function_release: 0,
  js_threadsafe_function_abort: 1,
  js_threadsafe_function_nonblocking: 0,
  js_threadsafe_function_blocking: 1,
  js_garbage_collection_type_mark_compact: 1,
  js_garbage_collection_type_generational: 2
}

exports.layouts = {
  js_platform_options_t: {
    size: 20,
    fields: {
      version: 0,
      expose_garbage_collection: 4,
      trace_garbage_collection: 5,
      disable_optimizing_compiler: 6,
      trace_optimizations: 7,
      trace_deoptimizations: 8,
      enable_sampling_profiler: 9,
      sampling_profiler_interval: 12,
      optimize_for_memory: 16
    }
  },
  js_platform_limits_t: {
    size: 12,
    fields: {
      version: 0,
      arraybuffer_length: 4,
      string_length: 8
    }
  },
  js_env_options_t: {
    size: 8,
    fields: {
      version: 0,
      memory_limit: 4
    }
  },
  js_property_descriptor_t: {
    size: 32,
    fields: {
      version: 0,
      name: 4,
      data: 8,
      attributes: 12,
      method: 16,
      getter: 20,
      setter: 24,
      value: 28
    }
  },
  js_delegate_callbacks_t: {
    size: 24,
    fields: {
      version: 0,
      get: 4,
      has: 8,
      set: 12,
      delete_property: 16,
      own_keys: 20
    }
  },
  js_type_tag_t: {
    size: 16,
    fields: {
      lower: 0,
      upper: 8
    }
  },
  js_callback_signature_t: {
    size: 16,
    fields: {
      version: 0,
      result: 4,
      args_len: 8,
      args: 12
    }
  },
  js_heap_statistics_t: {
    size: 16,
    fields: {
      version: 0,
      total_heap_size: 4,
      used_heap_size: 8,
      external_memory: 12
    }
  },
  js_heap_space_statistics_t: {
    size: 20,
    fields: {
      version: 0,
      space_name: 4,
      space_size: 8,
      space_used_size: 12,
      space_available_size: 16
    }
  },
  js_error_location_t: {
    size: 40,
    fields: {
      version: 0,
      name: 4,
      source: 8,
      line: 16,
      column_start: 24,
      column_end: 32
    }
  },
  js_garbage_collection_tracking_options_t: {
    size: 12,
    fields: {
      version: 0,
      start: 4,
      end: 8
    }
  }
}
